### PR TITLE
Fix react setState race condition

### PR DESCRIPTION
**Pull request by sherryxiao1988**
when multiple components need to call addToAutoFilledValues (I am using the avatar(xavcz:nova-forms-upload) plugn along with the subscription package), this.state is concurrently accessed/changed by multiple components when they are rendered. autofilledValues sometimes only holds the last value.

See here:
http://stackoverflow.com/questions/38065534/race-condition-in-react-setstate

### CODE REVIEW

**Comment by sherryxiao1988** [comment]
@xavcz please take a look :) I spent an afternoon to figure out what happened

**Comment by xavcz** [comment]
Ok I see! Nice one @sherryxiao1988!

note: Please next time do your PR on `devel` branch 👍

**Comment by Rongchao** [comment]
very nice

**Comment by meteorplus** [comment]
this is a very important fix and it should be in master!!

**Pull request merged**
