### PR TITLE
make useraccounts:unstyled optional

### PR DESCRIPTION
**Pull request by jshimko**
Fixes https://github.com/TelescopeJS/Telescope/issues/1048

This makes it so `useraccounts:unstyled` can be removed and replaced with one of the other styled options.

### CODE REVIEW

**Comment by SachaG** [comment]
Are there any downsides to having non-Telescope packages in there? What happens if someone removes `useraccounts:unstyled`?

**Comment by jshimko** [comment]
It would surely break stuff, but I don't see any other way to allow users to choose one of the other useraccounts styling packages.  And if someone is doing that manual removal step, it's probably safe to assume it was intentional and they know what they're doing, right?  (or at least know how to fix it)

We could tie it to one of the themes like Josh suggested, but then people would still be stuck with the package if they wanted to use the theme, but not the unstyled useraccounts templates.

**Comment by SachaG** [comment]
Well, let's think about it. Down the road one of our goals is to make it possible to drop in Telescope into any existing Meteor app. So maybe what we should do instead is separate `telescope:users` into `telescope:users` and `telescope:accounts`, and `useraccounts:unstyled` would be a dependency of `accounts`, not `users`? This way you'd only have to customize `accounts`. 

Doing it your way is easier of course, but I liked the idea of only having `telescope:xyz` packages…

**Comment by jshimko** [comment]
What would go in `telescope:accounts`?

**Comment by SachaG** [comment]
Basically all the `useraccounts` stuff.

**Comment by SachaG** [comment]
Actually we can't use your solution, because it would break people who update using `meteor update`… But that's true for my solution, too. I guess for now we have to keep the same package list.

But we could make `'useraccounts:unstyled` a dependency of `telescope:users` and not `telescope:lib`, that would already be an improvement.

**Comment by queso** [comment]
I am not sure I follow, what breaks on meteor update? You might get a newer version of useraccounts that might break things?

**Comment by SachaG** [comment]
@queso what will break is that people won't be able to update their app with just `meteor update`, since they would have to manually add `useraccounts:unstyled` to their package file.

**Comment by queso** [comment]
Why not move it to theme-base? It seems like I am totally going off reservation and not using that, but most will at least rely on theme-base for their custom theme, right?

**Comment by SachaG** [comment]
Yes, that's also an option.

**Pull request closed without merging**
