### PR TITLE
Adding newsletter time setting

### PR DESCRIPTION
**Pull request by anthonymayer**
Adding newsletterTime setting.

Still todo
- [ ] Add tests
- [ ] Add some more translations

### CODE REVIEW

**Comment by SachaG** [comment]
Should I merge it now, or wait until you add some tests?

**Comment by anthonymayer** [comment]
If you think it's good you're more than welcome to merge it and I can add tests as a follow up. Part of the reason I wanted to add tests is that I don't actually use the newsletter so I've only tested the setting part manually, I don't know the best way to test that the newsletter actually gets sent.

**Comment by SachaG** [comment]
Does the time use 24-hour or AM/PM notation? Also, can we make the default time 09:00 AM?

**Comment by anthonymayer** [comment]
@SachaG: Changing the default to 9:00 AM isn't a problem. I used 00:00 because that's what it looked like the default is currently. The time notation is actually based on the user's browser settings, because it uses the HTML5 time input tag. It looks like it always returns 24 hr values though no matter what the user sees.

**Comment by SachaG** [comment]
OK, sounds good :)

**Pull request merged**
