### PR TITLE
Customisable post-by-feed

### PR DESCRIPTION
**Pull request by em0ney**
- Adding ECMAScript2015 classes for customisable feed handlers
- Adding field on feeds to specify classname of feed handler
- Adding Setting for the frequency of feed collection

### CODE REVIEW

**Comment by SachaG** [comment]
Sorry, but can you remind me what this PR was for?

**Comment by SachaG** [comment]
Mainly to let users specify the feed parsing frequency I guess?

**Comment by em0ney** [comment]
Beyond that, it gives users the ability to put feed specific parsing logic (e.g. take item summary for one feed maybe description for another, amend the time for a specific timezone)

**Comment by SachaG** [comment]
My thoughts: I'm all for making Telescope easier to customize, but I feel like this might be going a little bit too far. The added flexibility is great, but at the same time I'm hesitant to introduce that much complexity in the codebase for something that's kind of a niche feature. 

So here's my suggestion: instead of enabling having different feed parsers for each feed, let's keep a single global feed parser that can be overridden by redefining the function. And if people want a different handler for different feeds, they can just make their own global feed parser that uses a `switch` based on the feed ID or something. What do you think?

Also as a small note, I would probably stick to camelCase (for stuff like `FEED_PARSER_FREQUENCY_PROPERTY_NAME`) unless there's a good reason not to.

**Comment by em0ney** [comment]
Totally your decision as whether to integrate the pull request into your codebase.  I think that the key thing missing in telescope and indeed many javascript codebases is OO and primarily encapsulation.  I think that part of striving to make Javascript and Meteor more mature is trying to encourage the development of its developers.

Thanks for looking anyway,
Elliott

**Comment by SachaG** [comment]
Well, the issue with this kind of PR is that you might not always be around to maintain that code… so I'm always hesitant to merge in code of a higher complexity level in the project, because it creates a higher barrier to entry for other people who might come in later.

So I'd like to get some more community feedback first, unless you feel confident that you can keep on maintaining that part of the app for the foreseeable future :)

**Comment by xavcz** [comment]
Hey, @em0ney! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this PR. However, the `post-by-feed` package has been ported to an external repo : https://github.com/xavcz/nova-post-by-feed. Contributions welcomed 👍 

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍

**Pull request closed without merging**
