### PR TITLE
Fix broken twitter avatars

### PR DESCRIPTION
**Pull request by bengott**
- services.twitter.profile_image_url_https field wasn't being published

### CODE REVIEW

**Comment by SachaG** [comment]
Thanks!

**Comment by SachaG** [comment]
Actually it still seems like something's broken? Looks to be a CSS issue. Did something change with that?

http://cl.ly/aCFo

**Comment by bengott** [comment]
No CSS changes. It was just failing because that twitter avatar url wasn't accessible client-side, so the img element had no src, and it was just showing the alt="avatar" text inside the div. Are you still having problems?

**Comment by SachaG** [comment]
Those are avatars of people who logged in with their email/password/username. So I don't know if the twitter thing has an impact on that?

**Comment by bengott** [comment]
Hmm, it should be trying to use Gravatar in that case, then falling back to initials if the image fails to load.. I'll look into it more later.

**Pull request merged**
