### PR TITLE
Mailchimp newsletter enhancement - remove deleted users, edit setting in user profile. 

### PR DESCRIPTION
**Pull request by jms301**
As per [issue](https://github.com/TelescopeJS/Telescope/issues/1079).

This change crate a new hook "onRemoveUserAsync".

### CODE REVIEW

**Comment by jms301** [comment]
Ok have now added in user config settings and a hook for when the user config changes. New hooks are: 

onRemoveUserAsync
and
onUpdateUserAsync

**Comment by capensisma** [comment]
Oh nice but can please keep the names format as used in telescope docs

userAccountRemoved

and

profileUpdateSync

Thanks

if we keep it like that we can fix and improve plenty of things

**Comment by jms301** [comment]
I don't see these hooks in the docs. I can only find [this](http://docs.telescopeapp.org/docs/callback-hooks) list of hooks, are there more somewhere else?

**Comment by SachaG** [comment]
Thanks for the great work. I'll probably wait until the next release to merge this in though, just to avoid having even more stuff change at the same time. Hope that's ok?

And yeah, we should have a standard syntax for defining hooks names. `onRemoveUserAsync` is not a bad name, but it's true it doesn't really follow the same pattern as the other ones. If we wanted to be consistent, it would be `userDeleteAsync`. I'm happy to discuss this though.

**Comment by jms301** [comment]
Ha sure I was just blatting issues. 

cool yea that is a better name for it. I don't mind what the name is just nice if there is a scheme. I'll update to your suggested names.

What for the update hook? userUpdateAsync?

**Comment by SachaG** [comment]
maybe `userEditAsync`?

**Pull request closed without merging**
