### PR TITLE
Create ar.i18n.json

### PR DESCRIPTION
**Pull request by nwabdou85**
ar.i18n.json  is the translation of  en.i18n.json

### CODE REVIEW

**Comment by SachaG** [comment]
Thanks! Merged into `devel`.

**Comment by nwabdou85** [comment]
you're welcome!  there are some items (words and phrases) in the application that I don't find in the en.i18n.json file!!

**Comment by SachaG** [comment]
Yeah, sorry about that. We need to take some time to clean up the whole i18n process, and maybe start using Transifex to keep track of everything.

**Comment by nwabdou85** [comment]
I understand you;
Is there à way to use only one language in Télescope and remove thé others??

**Comment by SachaG** [comment]
Are you worried about loading the extra files? Because you don't have to worry about that, only files for the current language are loaded to the client.

**Comment by nwabdou85** [comment]
No, what bothers me is when I refresh the page, it render the English version for a few seconds and after that it render the Arabic version; I think it's not a good user experience !! that's why I thought to leave only one language. What do you think !!

**Comment by SachaG** [comment]
Oh ok. In that case it's a bug, maybe you can open a new issue about it?

**Comment by nwabdou85** [comment]
yeh, I'll

**Comment by nwabdou85** [comment]
It's ok, now. Thank's a lot Sacha

**Comment by SachaG** [comment]
We're switching to [LingoHub(http://lingohub.com) to help manage translations. If you'd like to be added as a translator to the project, could you join the #i18n channel on [Telescope's Slack](http://slack.telescopeapp.org)?

**Comment by nwabdou85** [comment]
it' was a  pleasure  to join you;)  it's done

**Pull request closed without merging**
