### PR TITLE
minor fixes

### PR DESCRIPTION
**Pull request by capensisma**
on post submit and setting scroll to top when user click submit and shows a message

### CODE REVIEW

**Comment by SachaG** [comment]
Thanks, the settings thing is a good idea. But we can't change `Telescope.config.postStatuses` like this, the idea is that statuses should be only defined once in the app. 

Also, when internationalizing any string make sure you use a key (so `i18n.t('settings_saved')`, not `i18n.t('Settings Saved')`, and then add the translation to `i18n.en.json`.

**Comment by capensisma** [comment]
You're welcome.

i will work on more on the settings. i didn't know where the i18n.json is located that's why, but i know i should have used a key string for the i18n.

and for the Status i don't but if it should be defined once, so the field should be omitted for all user since i see it as an number input field.
it should be a hidden field. omit:true

The the pending post issue was solved but the still when you click a pending post 
it doesn't show post page, just a blank page.

**Comment by capensisma** [comment]
Please add the settings code so it will be easier to get to the top of the page after saving it 
thanks

**Comment by SachaG** [comment]
OK, I'll add it :)

**Comment by capensisma** [comment]
Thanks :dancer:

**Pull request closed without merging**
