### PR TITLE
Complete soft delete feature for comments

### PR DESCRIPTION
**Pull request by justintime4tea**
# List of changes
- Add new CommentsDelete component to nova-base-components
- Add new props and functions to CommentsItem for delete feature
- Hide edit, delete and reply UI elements in CommentsItem if comment isDeleted
- RegisterCommentsDelete with Telescope namespace in components.js
- Add style for comment-delete and comments-delete-form elements in _comments.scss
- Add style for novaform-cancel element in _other.scss
- Add isDeleted check before decrementing user and post comment count
- Change cancel element from <a> to <Button> in NovaForm
- Add submitButtonText prop to NovaForm to allow changing the Submit button text
- Add check for isDeleted to Users.can.edit permissions

Commit: [c922645](https://github.com/justintime4tea/Telescope/commit/c922645350fc544ecff6b9990837a7a6a44b9303)

Closes issue: #1314

### CODE REVIEW

**Comment by SachaG** [comment]
Sorry it took me a while to look at this! It all looks great, but I'm just wondering why you added a `CommentsDelete` component using NovaForms? Why not just call the method directly?

(See how posts are deleted here: https://github.com/TelescopeJS/Telescope/blob/devel/packages/nova-base-components/lib/posts/PostsEditForm.jsx#L19-L27 )

**Comment by justintime4tea** [comment]
That's a very good question Sacha :) I guess I hadn't taken a look at how Posts are deleted and instead jumped the gun on modifying the CommentsEdit. I'll take a look at the direct method call of posts delete and see if I can refactor this so it is more efficient/better.

**Comment by justintime4tea** [comment]
Refactored to use direct call, making new branch and new pull request.

**Comment by SachaG** [comment]
Sounds good, I'll check out the other PR then. Thanks again!

**Pull request closed without merging**
