### PR TITLE
Subscribe post

### PR DESCRIPTION
**Pull request by delgermurun**
Ref #452.

- Subscribe/Unsubscribe post
- When new comment added on user's subscribed posts, user receive notification.
- Show subscribed posts on user's profile
- Author can't subscribe own post (already sends notification)
- Change new comment's email notification subject, if post is subscribed post (not own post)
- Save subscriber count on post.

### CODE REVIEW

**Comment by SachaG** [comment]
I'm working on this. I might end up refactoring it a little bit :)

**Comment by delgermurun** [comment]
:+1:

**Comment by SachaG** [comment]
You can check out the results on the `devel` branch: https://github.com/TelescopeJS/Telescope/tree/devel

Main things I changed: 

- Rewrote the logic to decide which users to notify to be less confusing.
- Made `telescope-subscribe-to-posts` into its own package independent from the notification stuff. 
- A user's subscribed posts are now private and displayed on their user edit page, not their public user profile.
- The subscribe link is now at the bottom of the comment thread, not in the main post item.

Please review my changes and let me know what you think :)

I'm still testing out some stuff by the way, so it's probably not 100% bug-free yet…

**Comment by delgermurun** [comment]
@SachaG notification says "has replied to your comment on", but I don't reply, I just write root comment.

**Pull request merged**
