### PR TITLE
Add some basic cucumber.js tests and get them working on travisCI

### PR DESCRIPTION
**Pull request by queso**

### CODE REVIEW

**Comment by queso** [comment]
something is off with the travis config, not ready to merge yet.

**Comment by SachaG** [comment]
Any update on this?

**Comment by queso** [comment]
I should try this again :)

**Comment by xavcz** [comment]
Hey! That would be awesome to have working tests with Nova 🎉 

Can't merge this PR because of the old tests, I'm closing it.

**Pull request closed without merging**
