### PR TITLE
New i18n package - es_ES

### PR DESCRIPTION
**Pull request by beeva-franciscocalle**
Settings defined language is not been used (forced to "en")

### CODE REVIEW

**Comment by SachaG** [comment]
Thanks for the translation! But actually I've decided that translations should be separate repos (see https://github.com/TelescopeJS/nova-i18n-fr-fr). So if you host and publish the repo yourself, I'll just link to it from the docs :)

**Comment by beeva-franciscocalle** [comment]
Great, here is the repo: https://github.com/beeva-franciscocalle/nova-i18n-es-es

**Comment by SachaG** [comment]
Awesome. You'll also need to publish it to Meteor's package repo (`meteor publish --create`) before people can use it.

**Comment by beeva-franciscocalle** [comment]
Done, here is the link. I've changed to my personal account: https://atmospherejs.com/fcallem/nova-i18n-es-es

**Pull request closed without merging**
