### PR TITLE
small fix prerender https issue #1202

### PR DESCRIPTION
**Pull request by capensisma**
Fix of Issue https://github.com/TelescopeJS/Telescope/issues/1202

### CODE REVIEW

**Comment by SachaG** [comment]
Thanks! I actually fixed something else in that code so I'll just work in your changes manually.

**Comment by constantx** [comment]
@SachaG is the new fix on a branch somewhere that I can cherry pick for now till you update the package on github?

**Comment by SachaG** [comment]
It's on the devel branch.

**Comment by constantx** [comment]
got it, thanks :)

**Pull request closed without merging**
