### PR TITLE
Workaround categories permission and data type bug

### PR DESCRIPTION
**Pull request by yourcelf**
Workaround for https://github.com/aldeed/meteor-autoform/issues/765

Fixes issue #834.

### CODE REVIEW

**Comment by SachaG** [comment]
Thanks! Ideally this kind of thing should be fixed at the AutoForm/SimpleSchema level, but I guess for now we can do it that way.

We just need to make sure we don't forget to remove this once the bug gets fixed.

**Comment by SachaG** [comment]
This does seem a bit hacky though, let me ask @aldeed if he has a timeline to fixing that bug first before merging this :)

**Comment by aldeed** [comment]
I think I am going to go back to old behavior as default and allow people to opt in to the new behavior when they need to update specific array items rather than an entire array, and they know the array already exists in the database. It's not a perfect solution because you can't do both in the same form, but oh well.

I thought people would be OK with just working around the mongo issue themselves, ensuring that all array props are never null or undefined in the db, but it's causing a lot of consternation, so it's probably better for AF to continue masking the issue.

Hoping to release this change today.

**Comment by SachaG** [comment]
Thanks! I think that's the right decision for now. I don't mind working around the issue at the app level, but I think introducing that kind of breaking change is always a bit tricky, especially when it's not obvious what's going on (I wasn't familiar with the Mongo issue myself for example).

**Comment by SachaG** [comment]
Closing this PR since it shouldn't be necessary anymore :)

**Pull request closed without merging**
