### PR TITLE
Lowercase usernames and Email plus trim and space removal

### PR DESCRIPTION
**Pull request by splendido**
I've managed to update `useraccounts` to the latest version to enable trim/lowercase/remove_spaces on username, email and username_and_email fields.

...the only thing is I had to update iron:router to the latest version and meteor to 1.0.3.1.
To this aim I had to lock the version of other packages to prevent their update (it not me supposed to update packages I don't know how are used within Telescope... ;-) )

**Please give another try to this branch and do some test BEFORE mergin this!**

this should solve both #691 and #723.

### CODE REVIEW

**Comment by splendido** [comment]
mmm, I had in mind to PR to `devel` not to `master` :(
do you want me to make another PR and close this one?

**Comment by SachaG** [comment]
Sorry it's taken me so long to look into this. I tried your code and it seems to work :)

But I'm not sure if the UX is really what we want: right now it seems impossible to use *any* capitalization in usernames. So if I type "TechCrunch", it gets converted to "techcrunch" automatically. 

While I agree that we should ideally let people sign in with both "TechCrunch" and "techcrunch", I don't think forcing all usernames to lowercase is a great solution…

Sorry for not paying attention to that earlier :(

**Comment by queso** [comment]
So you see "Travis" and "travis" as different usernames?

**Comment by SachaG** [comment]
RIght now yes, you can sign up as both `Travis` or `travis`, and it'll create two user accounts.

**Comment by queso** [comment]
This is a fundamental bug in Meteor, not a feature :)

This issue has been around a while: https://github.com/meteor/meteor/issues/550

**Comment by splendido** [comment]
No worries @SachaG!
I understood you were comfortable with this, also fro the discussion about the migration process to convert username to lowercase and warning for possible conflicts ;-)
...btw, just let me know how you intended this and I'll be happy to update the code accordingly.

@queso would you be to keep it like this?

...or do you guys think leaving the username unchanged and considering it lowercased behind the scenes would provide for a better UX? (this might be a little tricker to implement, but not impossible by adding a few lines for this particula case...)

**Comment by SachaG** [comment]
Yes, it's my fault, I didn't look at this closely enough. The solution I had in mind was what you suggested, leaving the username unchanged and testing behind the scenes. 

For example, you could have two username fields (say, `username` and `usernameLowercase`) and use `usernameLowercase` for all uniqueness checks?

**Comment by splendido** [comment]
...mmm, what you're asking would require to change the Accounts package which is something I wouldn't  consider!

What about setting `username` always lowercased and keeping another  `profile.username` with the original case to be used on the client side to show it the way the user wanted it?

**Comment by SachaG** [comment]
Yes, that would also be a good solution. In fact that's already what Telescope does, except with `profile.name` (but I'm happy to change it to `profile.username` if that's cleaner).

**Comment by SachaG** [comment]
See: https://github.com/TelescopeJS/Telescope/blob/master/server/users.js#L29-L31

**Comment by splendido** [comment]
oh, I didn't know: I'm not that into Telescope's code, sorry!

...well, in this case it would be enough to add set `profile.name` to the original *username* when `Accounts.createUser` is called and everything should work accordingly! :-)

...I'd say we might add a check for *already existing username* on the sign up form so to prevent bad surprises: this is actually already possible see [this](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#custom-validation)
Thoughts?

**Comment by SachaG** [comment]
OK, but with this PR you can't enter capital letters at all:



So to recap, I think a good solution would be:

1. Let user enter whatever they want (`Sacha`)
2. Copy that to `profile.username`.
3. Change username to lowercase version (`sacha`)

Then when somebody wants to sign in or sign up, you convert what they entered to lowercase and check it against `username`. And inside the app, you only ever display `profileusername`. Sounds good?

**Comment by splendido** [comment]
Yeah, that's it!
...but if you're not keen to change all `profile.name` to `profile.username` through all the code, I can make it to set `profile.name` with the original `username` field content.
Actually I'll have to set one of the two in any case...

Btw, If you have one common helper to pick up `profile.name`, lets change that one! ;-)

I'll update useraccounts to have one more option to deal with this...

**Comment by splendido** [comment]
I've just updated the `lowercase-usernames` branch with the `devel` one!
So perhaps this PR should be closed and a new one made to make it into `devel`...

In any case, now it LGTM. I've done some simple tests by hands but if you could revise it a little more it would be great!
I guess you've a better idea about the possible implications...

for example, should we update also the `user.slug` field within the migration code?

**Comment by splendido** [comment]
Actual changes are better viewed with [this comparison](https://github.com/TelescopeJS/Telescope/compare/lowercase-usernames)

**Comment by SachaG** [comment]
Awesome. And yes, there's a single helper for displaying usernames: 

https://github.com/TelescopeJS/Telescope/blob/devel/lib/users.js#L24-L35

A new PR would be great. And I think we probably don't need to modify `user.slug`, since it was lowercase to begin with?

**Comment by splendido** [comment]
So [these lines](https://github.com/TelescopeJS/Telescope/blob/devel/lib/users.js#L26-27) should be changed to 

```javascript
    if (user.profile.username)
      return user.profile.username;
```

but then what's the reason for [getDisplayName](https://github.com/TelescopeJS/Telescope/blob/devel/lib/users.js#L36)?

**Comment by splendido** [comment]
[This](https://github.com/TelescopeJS/Telescope/compare/lowercase-usernames#diff-93aa3cd6516e4575bf93e79539665635R37) is what I changed from `getDisplayName`...

**Comment by SachaG** [comment]
Sorry you're right, we use `getDisplayName`, not `getUsername`. I should remove that one I guess.

**Comment by splendido** [comment]
...another thing which is coming to my mind is:
since I'm changing the `profile.name` field for the `profile.username` one, is there any other migration which is expecting the `profile.name` to exist?

**Comment by SachaG** [comment]
I don't think so. I'll test it out before merging anyway :)

**Comment by SachaG** [comment]
Just to confirm, is the PR ready on your side? Or should I wait?

**Comment by splendido** [comment]
It's ready for me, if you don't see any possible conflict with other stuff lets merge it ;-)

...if you prefer, lets make a manual  merge of `lowercase-usernames` into `devel`

**Comment by SachaG** [comment]
One thing I forgot to mention is that the “display name” (which is what we store in `profile.username` can include spaces or any characters). 

So to recap, we could have people entering `The Next Web` or `TheNextWeb`, and they should both resolve to `thenextweb`. 

It seems to be working fine right now, but I just wanted to make that clear :)

**Comment by SachaG** [comment]
Merged on `devel`.

**Comment by SachaG** [comment]
Oh btw, the migration was failing on users that don't have a username (for example those that signed up via Twitter).

**Comment by splendido** [comment]
yep, the `profile.username` is set to the original text entered at registration time!

...good call on the migration of users without a username! :(

**Comment by splendido** [comment]
an optional step further might be checking the availability of the selected username before form submission.
Everything is already supported (I also have an example about how to achieve this in the [custom validation](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#custom-validation) section): basically we can have a method called when the `username` input loses the focus (or whatever we prefer) and show a spinbox (or something...) next to the input to eventually let the user know whether the selected username is available or not before she clicks *Register*

Let me know if you think this could be good to have!
(it might open some *security* issues though, like automated username listing...)

**Comment by SachaG** [comment]
This would be a nice touch but it doesn't seem critical right now. I'm already very grateful for all the work you've done on this :)

**Comment by splendido** [comment]
My pleasure!

...next big step will be accounts melding ;-)

**Pull request closed without merging**
