### PR TITLE
Handle Deleted User In Email

### PR DESCRIPTION
**Pull request by johnthepink**
This fixes the issue of posts from deleted users showing up in an email campaign. It does two things:

1. Returns blank if trying to get the profile URL of a user that does not exist
2. Just displays "Submitted on" instead of "Submitted by user on" if the user does not exists

Here's an example:
screenshot 2015-06-18 21 54 59

Thanks!

### CODE REVIEW

**Comment by SachaG** [comment]
I'm actually just refactoring this part of the app, so I'll just merge this is manually. Thanks!

**Comment by SachaG** [comment]
Although, note that the author name is denormalized on the post, so we should always be able to show a name even if the user has deleted their account.

**Comment by SachaG** [comment]
Here's what I ended up doing: https://github.com/TelescopeJS/Telescope/commit/f437153d63a33d7e146346094b3c003b686d864e

**Comment by johnthepink** [comment]
@SachaG Nice! That is much nicer. Thanks for the heads up!

**Pull request closed without merging**
