### PR TITLE
Add explicit control for clearing out form fields

### PR DESCRIPTION
**Pull request by cenkce**
Test url : https://telescopeapp-cenkce.c9users.io/

### CODE REVIEW

**Comment by SachaG** [comment]
Nice progress! I would love to hear more about your thought progress though. For example why did you add logic in `FormComponent` instead keeping everything in `Form`? And why did you need to modify `DateTime`?

Ideally `FormComponent` should remain super simple, its job is only selecting the right component to display, not managing any kind of internal state. So the only stateful component here should be `Form`.

**Comment by SachaG** [comment]
Oh also what does `isDirty` do?

**Comment by cenkce** [comment]
isDirty state means component has a new value. Because FormComponent is the container component and I think it can manage data flow. Why did i modify datetime component? Beacuse 
1- this.context... is the experimental feature
2- Component doesn't fire onBlur event. Components' data flow is not standard and to my way of thinking this is the architectural problem. Some components' value is updated by FormComponent, others' value is updated by its own. It is confused. I think Single data flow is better solution.

FormComponent is the kind of decorater and container component and in my opinion The FormComponent logic (updating component value, adding clear button and clearing new value) is encapsulated within.

**Comment by SachaG** [comment]
Do you think you could modify the PR to keep `FormComponent` stateless?

**Comment by cenkce** [comment]
No problem I can do

**Comment by xavcz** [comment]
How I are you doing @cenkce?

**Comment by xavcz** [comment]
I believe we can close this, due to inactivity & conflict. Don't hesitate to re-open a new one or ask feedback @cenkce if you work again on that!! 🚀

**Pull request closed without merging**
