### PR TITLE
Settings package

### PR DESCRIPTION
**Pull request by delgermurun**

### CODE REVIEW

**Comment by SachaG** [comment]
I want to get the current release out soon, so I will wait a bit before merging this :)

**Comment by delgermurun** [comment]
@SachaG ok. If this solution is fine, I'm going to make comments package.

**Comment by SachaG** [comment]
Merging this manually.

**Comment by delgermurun** [comment]
:+1:

**Comment by SachaG** [comment]
I just noticed you change how extra settings properties are added:

```js
Settings.addToSchema = function(item) {
  var itemSchema = {};
  itemSchema[item.propertyName] = item.propertySchema;

  Settings.collection.attachSchema(itemSchema);
  Settings.schema = new SimpleSchema(Settings.schema, itemSchema);
};
```

I guess it works, even though `itemSchema` is not a `SimpleSchema` object?

**Comment by delgermurun** [comment]
yes it does.

**Pull request closed without merging**
