### PR TITLE
Update newsletter schedule

### PR DESCRIPTION
**Pull request by johnthepink**
This adds an option for each day of the week to Newsletter Frequency. Let me know if you have any changes! :smile_cat:

### CODE REVIEW

**Comment by SachaG** [comment]
Thanks! But we probably need a migration to port over the old settings, too?

**Comment by johnthepink** [comment]
Good point! I'll take a look soon. Thanks.

**Comment by jamiewilson** [comment]
Nice work @johnthepink. Thanks for implementing this!

**Comment by johnthepink** [comment]
@SachaG I added a migration for this. Hope I did it correctly :smile:. Please send any feedback. Thanks!

**Comment by SachaG** [comment]
Looks good! I think I'll wait until the next release to merge this, just so I have some time to test it out. But it's coming :)

**Comment by johnthepink** [comment]
@SachaG sounds good. :smile_cat:

**Comment by SachaG** [comment]
Does `on()` take an array as argument, too?

And have you been testing this in production by the way?

**Comment by SachaG** [comment]
Yeah seems like it does. I'll merge this to `devel` and test it out on Meta.

**Comment by johnthepink** [comment]
@SachaG 

Cool, let me know what you find. I haven't tested it in production. Just locally using the `getNextJob` method and others to make sure it was scheduling properly. Thanks!

**Pull request merged**
