### PR TITLE
Validate post's categories on server.

### PR DESCRIPTION
**Pull request by delgermurun**
Created PR for https://trello.com/c/yJIcIzuz/97-check-that-categories-are-real-categories-server-side

### CODE REVIEW

**Comment by SachaG** [comment]
Wait, shouldn't it be `post.categories.length !== categoryCount` ?

**Comment by delgermurun** [comment]
@SachaG Haha. Sure. I forgot to revert testing code :D.

**Comment by delgermurun** [comment]
@SachaG updated.

**Comment by SachaG** [comment]
thanks :)

**Pull request merged**
