### PR TITLE
Improve newsletter

### PR DESCRIPTION
**Pull request by sungwoncho**
Trim HTML-stripped version of the post body, because trimming `post.body` gives unexpected results.

e.g.

If post.body was `### Title\n\n * list item 1 * list item 2`, it appears in the newsletter as  `<h3 id="title-list-item-">Title * list item…</h3>`

### CODE REVIEW

**Comment by sungwoncho** [comment]
Cannot figure out how to display avatars because I cannot use `avatar` template in the server side rendering (see https://github.com/meteor-utilities/avatar/issues/3). 

Don't want to duplicate it. Any suggestions?

**Comment by SachaG** [comment]
Thanks, sorry it took me so long to merge this! I ended up modifying the styling a bit, I hope you don't mind :)

**Comment by sungwoncho** [comment]
Not at all. This PR does not include displaying of avatar for commenters.

**Comment by SachaG** [comment]
Yeah. We can add that once the avatar package supports it.

**Pull request merged**
