### PR TITLE
Enabled the share buttons on desktop version

### PR DESCRIPTION
**Pull request by capensisma**
added display block
:)

### CODE REVIEW

**Comment by SachaG** [comment]
Haha, I wish it was that easy… The main question is how to integrate it in the layout.

**Comment by valgalin** [comment]
How about enabling the share button in the post's page? Hide the comment
icon, and display the share button?

On Sat, Aug 1, 2015 at 10:41 AM, Sacha Greif <notifications@github.com>
wrote:

> Haha, I wish it was that easy… The main question is how to integrate it in
> the layout.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TelescopeJS/Telescope/pull/1090#issuecomment-126853382>
> .
>



-- 
*Regards,*
Val Galin

*Let's be friends! :)*
t: @valgalin <http://twitter.com/valgalin>
g+: +ValGalin <https://plus.google.com/+ValGalin>

**Comment by valgalin** [comment]
It's just like how it's implemented on Screenings.io, sharing buttons are
in the post's page. Thoughts?

On Sat, Aug 1, 2015 at 10:58 AM, Val Galin <val.galin@gmail.com> wrote:

> How about enabling the share button in the post's page? Hide the comment
> icon, and display the share button?
>
> On Sat, Aug 1, 2015 at 10:41 AM, Sacha Greif <notifications@github.com>
> wrote:
>
>> Haha, I wish it was that easy… The main question is how to integrate it
>> in the layout.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/TelescopeJS/Telescope/pull/1090#issuecomment-126853382>
>> .
>>
>
>
>
> --
> *Regards,*
> Val Galin
>
> *Let's be friends! :)*
> t: @valgalin <http://twitter.com/valgalin>
> g+: +ValGalin <https://plus.google.com/+ValGalin>
>



-- 
*Regards,*
Val Galin

*Let's be friends! :)*
t: @valgalin <http://twitter.com/valgalin>
g+: +ValGalin <https://plus.google.com/+ValGalin>

**Comment by SachaG** [comment]
Yeah that could work in theory, but in practice both pages just include the same template. I wonder if it's worth making the logic more complex just for this…

**Comment by valgalin** [comment]
Hi Sacha, That's what my first thinking: it's a hassle logically. But it
occur to me that I have successfully hidden the discuss icon on the Iris
theme's single post via CSS.

So I made a PR where I showed the share button on the post's page and hide
the discuss icon. Thoughts? :)

On Sat, Aug 1, 2015 at 11:34 AM, Sacha Greif <notifications@github.com>
wrote:

> Yeah that could work in theory, but in practice both pages just include
> the same template. I wonder if it's worth making the logic more complex
> just for this…
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TelescopeJS/Telescope/pull/1090#issuecomment-126856909>
> .
>



-- 
*Regards,*
Val Galin

*Let's be friends! :)*
t: @valgalin <http://twitter.com/valgalin>
g+: +ValGalin <https://plus.google.com/+ValGalin>

**Pull request closed without merging**
