### PR TITLE
Assign feed item's categories to post.

### PR DESCRIPTION
**Pull request by delgermurun**
Assign feed item's categories to post.
Changed htmlparser2 to node-feedparser

### CODE REVIEW

**Comment by SachaG** [comment]
Awesome work. The only thing I would suggest is maybe comment the code a little bit more? Especially the categories stuff, since there's a lot of different variables with similar names.

**Comment by SachaG** [comment]
Merged on `devel`.

**Comment by SachaG** [comment]
Why is there an `if` here? 

https://github.com/delgermurun/Telescope/blob/post-by-feed-fix/packages/telescope-post-by-feed/lib/server/fetch_feeds.js#L33

Shouldn't we want to add feed categories even if the item has no RSS categories? Or maybe I don't understand that part?

**Comment by SachaG** [comment]
Oh ok never mind, I get it. I think I would just do `itemCategories.concat(feedCategories)`, it's ok if `itemCategories` is empty.

**Comment by SachaG** [comment]
Let me know what you think of my changes: https://github.com/TelescopeJS/Telescope/commit/7be7276980909a2d7b5770c9086ce12094fcd67c :)

**Comment by delgermurun** [comment]
@SachaG nice refactor :+1: I forgot about duplicating :)

**Pull request closed without merging**
