### PR TITLE
Add Dutch translation

### PR DESCRIPTION
**Pull request by doncitta**
My first pull request on Telescope app ,))
Add Dutch translation for 'telescope-singleday' package.

### CODE REVIEW

**Comment by SachaG** [comment]
Thanks! But since this is a package, you'll also have to import the file in `package.js` :)

**Comment by doncitta** [comment]
Yep, I have to. Thank you again!

**Comment by doncitta** [comment]
Yesterday I read your ‘Open Source Lessons Learned’, great analysis, I did a recommendation-tweet on @webfuts.
I actually see tons of frameworks struggling and probably die on the way because of underestimating the intensity of serve open source.

I hope & bet Telescope with Meteor will grow solid & steady. 
How more I dive in to the code how more clear everything gets cause all is so logic.

Sometimes I run into minor errors around Telescope. 
I like to report these small issues helping keping it coherent and remaining reliable. What the best way to do? 
Direct via mail hello@telesc.pe <mailto:hello@telesc.pe>, Github?

On page http://www.telescopeapp.org/docs/customizing/theming-telescope/ <http://www.telescopeapp.org/docs/customizing/theming-telescope/> there’s a 404 on 
Note: the code for this tutorial is available in the Telescope repository.

Arthur

**Comment by SachaG** [comment]
You can report issues here on GitHub :)

And sorry I haven't had time to merge your PR yet, it's on the to-do list :)

**Comment by SachaG** [comment]
Merged on devel branch.

**Comment by SachaG** [comment]
We're switching to [LingoHub](http://lingohub.com) to help manage translations. If you'd like to be added as a translator to the project, could you join the #i18n channel on [Telescope's Slack](http://slack.telescopeapp.org)?

**Pull request closed without merging**
