### PR TITLE
fix for peerDependencies requirements!

### PR DESCRIPTION
**Pull request by meteorplus**
downgraded to 0.14.8
formsy is making some bad trouble here better use the nice bootstrap forms? :) please?

thanks :)

### CODE REVIEW

**Comment by justintime4tea** [comment]
peerDependencies warning has already been addressed in latest devel branch. 
No need to downgrade React, formsy version 0.18 will now use React@^15.0.1

`git clone https://github.com/TelescopeJS/Telescope`
`cd Telescope/`
`git checkout devel`
`npm install`
`meteor'

If you prefer the bootstrap forms feel free to create a Telescope package which replaces the functionality of NovaForm component using bootstrap forms and issue a pull request.

This would be an awesome contribution and allow users to choose between either formsy or bootstrap.

**Comment by SachaG** [comment]
@justintime4tea well Formsy itself uses Bootstrap, so I don't know if we need another Bootstrap version. Also I'm not sure if React-Bootstrap by itself provides the same kind of form wrapping logic that things like Formsy or Redux-Forms do. Although I'll admit I'm still pretty new to React forms so I could be wrong.

**Comment by justintime4tea** [comment]
Aw, makes sense. I wasn't familiar at all with the Bootstrap Forms the person above us was talking about. Good to know.

**Comment by capensisma** [comment]
me too I don't know this person above lol :D

**Comment by xavcz** [comment]
The deps issue got fixed earlier 🎉 🎋

**Pull request closed without merging**
