### PR TITLE
add post._id as a childContextType for access by custom forms, and placeholder support for custom forms

### PR DESCRIPTION
**Pull request by sweetppro**

### CODE REVIEW

**Comment by SachaG** [comment]
Thanks, I'll check out the placeholder stuff! Not sure about the `_id` thing though. Maybe a more generic way to do it would be to pass NovaForm's `getDocument()` down through the context?

**Comment by sweetppro** [comment]
sounds good, i didn't want to pass to much down, so figured just the _id would be enough for customisations

**Comment by SachaG** [comment]
Well, if you just pass the method you're not actually passing anything down. So I think it's a good compromise.

**Comment by SachaG** [comment]
I'm going to do the changes manually. Btw, for future PRs make sure they're made to the `devel` branch :)

**Pull request closed without merging**
