### PR TITLE
Add topLevelCommentId field to comments.

### PR DESCRIPTION
**Pull request by cerupcat**
This allows childComments to know what the top most parent comment is by adding a topLevelCommentId to each childComment.

### CODE REVIEW

**Comment by SachaG** [comment]
Awesome, thanks!

**Comment by cerupcat** [comment]
Great - thanks SachaG. You're fast! :)

**Comment by SachaG** [comment]
Taking another look at this, I don't think we can keep that migration. There's three nested `forEach` loops in there, and I'm not sure if that's a good idea for sites like Crater that already have a lot of comments…

Maybe we just need to leave current data alone and assume the `topLevelCommentId` property might not always exist?

**Comment by cerupcat** [comment]
Yeah, I mean, if people don't need this for old comments threads, then it shouldn't be a big deal to not have a migration. I was't sure how to do the migration any simpler.

**Comment by SachaG** [comment]
Yeah I don't know how you could do it simpler either. It's more about doing it with https://github.com/percolatestudio/meteor-migrations or some similar system that can account for how long it'll take. Telescope's current migrations system is pretty bare-bones, so it can mess up with the deploy process.

**Pull request merged**
