### PR TITLE
React unit testing WIP

### PR DESCRIPTION
**Pull request by shilman**
First failed attempt at unit testing react components. Work in progress.

### CODE REVIEW

**Comment by shilman** [comment]
@tmeasday Wondering if you could take a quick look. @SachaG has structured Telescope using meteor packages, so the pattern I used for `Todos` doesn't work. Tried to run this test using:

```
cd packages/nova-base-components/
meteor test-packages ./ --driver-package practicalmeteor:mocha
```

But it can't find any of the dependencies (`react`, `react-meteor-data`, etc.) although as far as I can tell they are being properly `api.use`'d. And even if it could, I'm not sure how I'd add the `enzyme` NPM dependency for the test-only case.

I think I'm missing something about package testing, or perhaps this is a pathological case that sits between the old-style package testing, and the new-stye app unit testing?

**Comment by shilman** [comment]
@tmeasday Perhaps related to this? https://github.com/meteor/meteor/issues/6827

**Comment by tmeasday** [comment]
@shilman are the `react` et al also npm packages? 

I think you are reading this right, and it'll be fixed in 1.3.3. For enzyme, you'd need to add it as a `devDependency` to the app that you are running `test-packages` from (or if you are testing a package directly, add a `package.json` and `npm install` inside the package before running `test-packages`).

**Comment by shilman** [comment]
@tmeasday 

I added an `Npm.depends` for `react` and `react-addons-pure-render-mixin` to the `nova:base-components` package.js, but this did not fix anything. Many of Telescope's the packages depend on React but never actually declare it. But because Telescope uses package.json at the app level for installing `react` everything works.

I upgraded to `METEOR@1.3.3-beta.2` for good measure, though I don't think it's necessary. Get the exact same error as before upgrading.

I also tried adding a `package.json` with `react`, etc. in the `nova-base-components` package dir, but did not check it in. I think you meant this was just for `enzyme`, but I haven't gotten to that problem yet.

**Comment by tmeasday** [comment]
@shilman what is the exact error you get when you run that `test-packages` command?

**Comment by shilman** [comment]
@tmeasday 

```
MBP:nova-base-components shilman$ meteor test-packages ./ --driver-package practicalmeteor:mocha
[[[[[ Tests ]]]]]                             

=> Started proxy.                             
=> Started MongoDB.                           
W20160602-23:28:29.894(9)? (STDERR) WARNING: npm peer requirements (for react-meteor-data) not installed:
W20160602-23:28:30.014(9)? (STDERR)  - react@15.x not installed.
W20160602-23:28:30.014(9)? (STDERR)  - react-addons-pure-render-mixin@15.x not installed.
W20160602-23:28:30.014(9)? (STDERR)           
W20160602-23:28:30.015(9)? (STDERR) Read more about installing npm peer dependencies:
W20160602-23:28:30.015(9)? (STDERR)   http://guide.meteor.com/using-packages.html#peer-npm-dependencies
W20160602-23:28:30.016(9)? (STDERR)           
W20160602-23:28:30.377(9)? (STDERR)           
W20160602-23:28:30.377(9)? (STDERR) /Users/shilman/.meteor/packages/meteor-tool/.1.3.3-beta.2.mprozz++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20160602-23:28:30.378(9)? (STDERR)             				throw(ex);
W20160602-23:28:30.378(9)? (STDERR)             				      ^
W20160602-23:28:30.378(9)? (STDERR) Error: Can't find npm module 'react'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
W20160602-23:28:30.379(9)? (STDERR)     at Object.Npm.require (/private/var/folders/xl/1sqjz3zj1vx0pg39jdkz3qgm0000gn/T/meteor-test-run1pejdi9/.meteor/local/build/programs/server/boot.js:203:17)
W20160602-23:28:30.379(9)? (STDERR)     at options.fallback (packages/modules-runtime/modules-runtime.js:21:1)
W20160602-23:28:30.379(9)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:88:1)
W20160602-23:28:30.379(9)? (STDERR)     at meteorInstall.node_modules.meteor.react-meteor-data.createContainer.jsx (packages/react-meteor-data/createContainer.jsx:5:1)
W20160602-23:28:30.380(9)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
W20160602-23:28:30.380(9)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
W20160602-23:28:30.380(9)? (STDERR)     at meteorInstall.node_modules.meteor.react-meteor-data.react-meteor-data.jsx (packages/react-meteor-data/react-meteor-data.jsx:7:25)
W20160602-23:28:30.381(9)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
W20160602-23:28:30.381(9)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
W20160602-23:28:30.381(9)? (STDERR)     at /private/var/folders/xl/1sqjz3zj1vx0pg39jdkz3qgm0000gn/T/meteor-test-run1pejdi9/.meteor/local/build/programs/server/packages/react-meteor-data.js:319:15
=> Exited with code: 8                        
```

**Comment by tmeasday** [comment]
Cool. And is there a `react` package in `node_modules` inside that package's dir?

**Comment by shilman** [comment]
Yep. I added a `package.json` with the same react dependency as the App's dependency, though I didn't check it in to this PR since I'd assumed the `NPM.depends` does something similar but in the build output.

Here's an excerpt of the directory structure:
```
.
└── node_modules
    ├── react
    │   ├── dist
    │   └── lib
    ├── react-addons-pure-render-mixin
```

**Comment by tmeasday** [comment]
@shilman, I think that should work then. Here's the issue where this problem as fixed: https://github.com/meteor/meteor/issues/6827

I don't think you want the `Npm.depends()` -- this is a "peer" dependency on `react`.

**Comment by shilman** [comment]
@tmeasday I removed the Npm.depends (though technically I think it *should* be there, because the package does depend on React?) and committed the `package.json`. Still get the same error.

**Comment by tmeasday** [comment]
You can't use `Npm.depends` for peer dependencies (i.e. dependencies you want to share with other packages, such as `react`). See: http://guide.meteor.com/writing-atmosphere-packages.html#peer-npm-dependencies

**Comment by tmeasday** [comment]
I'm not sure about the error though. Perhaps we need to put a simple reproduction together.

**Comment by shilman** [comment]
Thanks @tmeasday I'll put together a simple repro this weekend and let you know when it's ready!

**Comment by shilman** [comment]
@tmeasday I tried to create a minimal repro, but unfortunately (fortunately?) the repro works properly:

https://github.com/shilman/meteor-package-test-spike

However, the Telescope version continues to give the same error as before. Currently `package.json` is 100% identical between the two projects, and `package.js` are virtually identical, with the Telescope version pulling in more dependencies.

**Comment by shilman** [comment]
@tmeasday I'm going to drop this direction since I'm under the impression that there will be a wholesale move to NPM packages soon and this appears to be a corner case. If you think there's value to Meteor in pursuing this, I'm happy to spend another few hours on it, just let me know. Closing for now...

**Comment by tmeasday** [comment]
Sounds reasonable @shilman

**Pull request closed without merging**
