### PR TITLE
#1458-First draft of customized scoring algorithm

### PR DESCRIPTION
**Pull request by S4KH**
#1458 Need more guidance on this. :sos:

### CODE REVIEW

**Comment by xavcz** [comment]
Will have a look in the weekend 💯

**Comment by S4KH** [comment]
Need help on calling callbacks from the `Telescope.updateScore` function. There are 3 callbacks added to the `scoring.all` hook(learned from the video :smile: ). Some of them does status check. When all of them on 1 hook what is the sequence of the calls?

**Comment by SachaG** [comment]
@S4KH thanks for taking the lead on this! To answer your questions, callbacks will just be called in the same order that they were added.

**Comment by S4KH** [comment]
How pass parameters to the callbacks? They all have different number of parameters, some callbacks return value that needs to be used as a parameter another function call. `ItemAgeCheck` returns `ageInHours` which must be passed to `PowerAlgorithm`.

**Comment by SachaG** [comment]
You can see how callbacks are called here: 

https://github.com/TelescopeJS/Telescope/blob/master/packages/nova-lib/lib/callbacks.js#L36-L73

The basic format is:

```
Telescope.callbacks.run(callbackName, iteratedItem, invariant1, invariant2, ...)
```
So you could do:

```
const newScore = Telescope.callbacks.run("scoring.all", item)
```

And then each successive callback would modify and return `item`. Or maybe:

```
const newScore = Telescope.callbacks.run("scoring.all", score, item)
```

In which case each callback would modify and return `score`, while passing `item` as an invariant to every callback. Does that make sense?

**Comment by S4KH** [comment]
@SachaG Thanks for your quick response. Then how do stop callback iteration when 1 of the checks fail. 

    if (!!item.status && item.status !== 2) // if item has a status and is not approved, don't update its score
        return 0;

**Comment by SachaG** [comment]
I think if you need to stop the iteration completely, it needs to be done outside the callback loop. There's no way of stopping callbacks right now.

**Comment by xavcz** [comment]
How are you doing @S4KH? 🙂

**Comment by S4KH** [comment]
Kind of stuck. Because of parameter passing to a callback.

**Comment by SachaG** [comment]
@S4KH maybe you can drop by the Slack chatroom if you have any questions?

**Comment by xavcz** [comment]
Hey @S4KH, thanks for what you've done! 🙌 

This PR is in conflict with the new version of Nova, powered with GraphQL: I'm closing it and will continue the work based on what you've done 💯

**Pull request closed without merging**
