### PR TITLE
Infinite Scroll Feature

### PR DESCRIPTION
**Pull request by meteorplus**
Check it out :)

### CODE REVIEW

**Comment by capensisma** [comment]
though it should check the current view is not daily so it won't load all days

**Comment by andmitsch** [comment]
Haha... that's like the most lazy, but functional approach to make an infinite scrolling method.

Like that...

**Comment by capensisma** [comment]
Lazy but working loool

**Comment by xavcz** [comment]
Hey, folks! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this PR.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍

**Pull request closed without merging**
