### PR TITLE
i18n added romanian translation based on the german translation strings

### PR DESCRIPTION
**Pull request by razvansky**
Issue #808 
I have added the ro.i18n.json to the i18n folder (based on our discussion in issue #808 use transifex for translation; transifex seem to have po files).

I will proceed to check the german translation de.i18n.json against en.i18n.json as I am afraid some strings are missing.

### CODE REVIEW

**Comment by razvansky** [comment]
Sorry if I used the master branch, I will make an i18n branch next time :panda_face:

**Comment by SachaG** [comment]
Yeah, using the `devel` branch is better but no worries. Thanks for the translation!

**Comment by SachaG** [comment]
Merged on `devel`.

**Comment by SachaG** [comment]
We're switching to [LingoHub](http://lingohub.com) to help manage translations. If you'd like to be added as a translator to the project, could you join the #i18n channel on [Telescope's Slack](http://slack.telescopeapp.org)?

**Pull request closed without merging**
